config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#root'

  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new, :show, :index]

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show]
    resources :spots, only: [:index, :new, :create, :show] #do
      # resources :reviews, only: [:show]
    #end
    get 'spots/search', to: 'spots#search'
    resources :reviews, only: [:index, :create, :show, :update, :destroy]
    resources :taggings, only: [:index, :create, :show, :destroy]
    resources :tags, only: [:index, :create, :show]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  after_initialize :ensure_session_token

  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, :session_token, uniqueness: true
  validates(
    :email,
    :first_name,
    :last_name,
    :password_digest,
    :session_token,
    :wanderer_title,
    presence: true
  )

  has_many :reviews
  has_one :picture, as: :imageable

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  private

  def generate_session_token
    SecureRandom::urlsafe_base64
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    render :show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in!, only: [:index]
  before_action :require_logged_out!, only: [:new, :create]

  def index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(email: user_params[:email],
                     first_name: user_params[:first_name].capitalize,
                     last_name: user_params[:last_name].capitalize,
                     password: user_params[:password])

    if @user.save
      Picture.create( name: "User Picture",
                      source: Faker::Avatar.image(@user.email, "200x200", "png", "set1", "bg1"),
                      imageable_id: @user.id,
                      imageable_type: "User")
      login_user!(@user)
      redirect_to :root
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password)
  end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Current_user: <%= current_user.email %></h1>
<%= current_user.first_name %>
<%= current_user.last_name %>
<br>
<%= current_user.wanderer_title %>

app/views/users/new.html.erb
<div class="log-in-background"></div>

<div class="log-in-page">
  <div class="center sign-in-logo">
    <img src="/assets/WanderSF.png"
         alt="Wander SF logo"
         height="90"
         width="300">
    </img>
  </div>

  <h3 class="sign-in-text center">Sign Up</h3>

  <br><br>

  <div class="sign-in-box center">
    <div class="row col-xs-4 col-xs-offset-4">
      <form action="<%= users_url %>" method="post">
        <%= auth_token %>
        <div class="form-group">
          <input type="email" class="form-control" name="user[email]" value="" placeholder="email">
        </div>

        <div class="form-group">
          <input type="password" class="form-control" name="user[password]" value="" placeholder="password">
        </div>

        <div class="form-group">
          <input type="text" class="form-control" name="user[first_name]" value="" placeholder="first name">
        </div>

        <div class="form-group">
          <input type="text" class="form-control" name="user[last_name]" value="" placeholder="last name">
        </div>

        <button type="submit" class="btn btn-primary center-block">Sign Up!</button>
      </form>

      <br>

      <p>Already have an account? <%= link_to "Sign in here!", new_session_url %></p>
    </div>
  </div>
</div>