config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#root'

  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new, :show, :index]

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show]
    resources :spots, only: [:index, :new, :create, :show] #do
      # resources :reviews, only: [:show]
    #end
    get 'spots/search', to: 'spots#search'
    resources :reviews, only: [:index, :create, :show, :update, :destroy]
    resources :taggings, only: [:index, :create, :show, :destroy]
    resources :tags, only: [:index, :create, :show]
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :rating, inclusion: { in: [1, 2, 3, 4, 5],
    message: "Rating must be between 1-5."}
  validates :spot_id, :user_id, :rating, presence: true
  validates :user_id, uniqueness: { scope: :spot_id,
    message: "You can only review a spot once"}

  belongs_to :spot
  belongs_to :user
end

app/models/spot.rb
class Spot < ActiveRecord::Base
  validates :name, :lat, :lng, presence: true
  validates :approved, inclusion: { in: [true, false],
    message: "Can only be set to true or false"}

  has_many :reviews
  has_many :taggings
  has_many :tags,
    through: :taggings,
    source: :tag
  has_many :pictures, as: :imageable
  has_one :spot_address

  def self.find_by_tag_partial(str)
    partial = "%#{str}%"
    Spot.includes(:tags).references(:tags).where("tags.name LIKE ?", partial)
  end

  def self.find_by_spot_partial(str)
    partial = "%#{str.downcase}%"
    Spot.where("lower(name) LIKE ?", partial)
  end
end

app/models/spot_address.rb
class SpotAddress < ActiveRecord::Base
  validates :spot_id, :street_address, :city, :state, :zip, presence: true
  validates :spot_id, uniqueness: true

  belongs_to :spot
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :taggings, dependent: :destroy
  has_many :spots, through: :taggings, source: :spot

  def self.queried_tags(str)
    partial = "%#{str.downcase}%"
    Tag.where("lower(name) LIKE ?", partial)
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  validates :spot_id, :tag, presence: true
  validates :spot_id, uniqueness: { scope: :tag_id,
    message: "Spot has already been assigned this tag"}

  belongs_to :spot
  belongs_to :tag


  # may use inverse_of
  def self.new_with_tag(tag_data)
    tag = Tag.find_by_name(tag_data[:name]) || Tag.create(name: tag_data[:name].capitalize)
    tagging = tag.taggings.new(spot_id: tag_data[:spot_id])
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  after_initialize :ensure_session_token

  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, :session_token, uniqueness: true
  validates(
    :email,
    :first_name,
    :last_name,
    :password_digest,
    :session_token,
    :wanderer_title,
    presence: true
  )

  has_many :reviews
  has_one :picture, as: :imageable

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  private

  def generate_session_token
    SecureRandom::urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :current_user_id, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def current_user_id
    current_user ? current_user.id : nil
  end

  def logged_in?
    !!current_user
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.session_token = nil
    session[:session_token] = nil
  end

  def require_logged_in! ## use for writing reviews
    redirect_to new_session_url if current_user.nil?
  end

  def require_logged_out!
    redirect_to root_url if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_in!, only: [:destroy]
  before_action :require_logged_out!, only: [:new, :create]

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
    params[:user][:email],
    params[:user][:password]
    )

    if @user
      login_user!(@user)
      redirect_to :root
    else
      flash[:errors] = ["Invalid username/password combination"]
      redirect_to new_session_url
    end
  end

  def destroy
    logout_user!
    render :new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_logged_in!

  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in!, only: [:index]
  before_action :require_logged_out!, only: [:new, :create]

  def index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(email: user_params[:email],
                     first_name: user_params[:first_name].capitalize,
                     last_name: user_params[:last_name].capitalize,
                     password: user_params[:password])

    if @user.save
      Picture.create( name: "User Picture",
                      source: Faker::Avatar.image(@user.email, "200x200", "png", "set1", "bg1"),
                      imageable_id: @user.id,
                      imageable_type: "User")
      login_user!(@user)
      redirect_to :root
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password)
  end
end

app/helpers/api/reviews_helper.rb
module Api::ReviewsHelper
end

app/helpers/api/spots_helper.rb
module Api::SpotsHelper
end

app/helpers/api/taggings_helper.rb
module Api::TaggingsHelper
end

app/helpers/api/tags_helper.rb
module Api::TagsHelper
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    html = <<-HTML
      <input type="hidden"
             name = "authenticity_token"
             value = "#{form_authenticity_token}">
    HTML

    html.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WanderSF</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300italic,300,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Alegreya:400,700' rel='stylesheet' type='text/css'>
  <script src="http://widget.cloudinary.com/global/all.js" type="text/javascript">
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAe7wJ7_QURxvvX7qt0yMQWoDEaGZvzQpQ"
          type="text/javascript"></script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-72678929-1', 'auto');
    ga('send', 'pageview');
  </script>
  </head>
<body>
  <% if current_user %>
    <script>
  	window.CURRENT_USER_ID = <%= current_user.id %>
    </script>
  <% end %>

  <%= render partial: "shared/errors" %>
    <%= yield %>
  <%= render partial: "shared/footer" %>
</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors]%>
  <div class="errors">
    <% messages = flash[:errors]%>
    <% messages.each do |message| %>
      <p class="flash"><%= message %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer">
    <ul>
      <li><a href="https://github.com/stephanie-lee"><img src="/assets/Github-mark.png"
           alt="GitHub logo"
           height="25"
           width="25"> Github</a></li>
    </ul>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
<div class="container-fluid">
  <div class="navbar-header">
    <%= link_to(image_tag("WanderSF.png",
                :alt => "Wander SF logo",
                :size => "200x60"),
                '/', :id => "WanderSFlogo") %>
  </div>

  <nav class="navbar-nav navbar-right">
    <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#collapse-menu"
            aria-expanded="false">
      <span class ="icon-bar"></span>
      <span class ="icon-bar"></span>
      <span class ="icon-bar"></span>
    </button>

  <div class="collapse navbar-collapse" id="collapse-menu">
    <ul class="nav navbar-nav">
      <li><a href="#">link one</a></li>
      <li><a href="#">link two</a></li>
      <li><a href="#">link three</a></li>
      <% if current_user %>
        <li><%= button_to "Sign Out", session_url, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign In", new_session_url %></li>
        <li><%= link_to "Sign Up", new_user_url %></li>
      <% end %>

    </ul>
  </div>
</nav>
</div>
</header>

app/views/shared/_login.html.erb
<% if logged_in? %>
  <p>Logged in as: <%= current_user.first_name %></p>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% end %>

<% if current_user %>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Sign In!", new_session_url %>
  <%= link_to "Sign Up!", new_user_url %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#collapse-menu"
            aria-expanded="false">
      <span class ="icon-bar"></span>
      <span class ="icon-bar"></span>
      <span class ="icon-bar"></span>
    </button>

  <div class="collapse navbar-collapse" id="collapse-menu">
    <ul class="nav navbar-nav pull-left">
      <li><%= image_tag("WanderSF.png", :alt => "Wander SF logo", :size => "200x60") %></li>
      <li><a href="#">link one</a></li>
      <li><a href="#">link two</a></li>
      <li><a href="#">link three</a></li>
      <% if current_user %>
        <li><%= button_to "Sign Out", session_url, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign In", new_session_url %></li>
        <li><%= link_to "Sign Up", new_user_url %></li>
      <% end %>

    </ul>
  </div>
</div>
</nav>